[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
test = 'test/foundry'
sparse_mode = true
cache_path = 'forge-cache'
solc = '0.8.23'
optimizer = true
optimizer_runs = 2000
via_ir = true
ignored_error_codes = ['unused-param']

[fmt]
bracket_spacing = true
multiline_func_header = params_first

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
