[profile.default]
  libs = ["node_modules", "lib"]
  sparse_mode = true
  solc = '0.8.23'
  optimizer = true
  optimizer_runs = 100000
  via_ir = true
  ignored_error_codes = ['unused-param']

[profile.lite]
  optimizer = false
  ignored_error_codes = ["code-size"]

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY_MAINNET}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY_SEPOLIA}"

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
